version: '3.7'

services:
  app:
    container_name: my_achievements_fe
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    env_file:
      - ../.env
    volumes:
      - '../:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000